name: test_on_each_pr

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: checkout code

      - name: run test cases
        run: |
          echo "Hello World"
          test -f test_file.txt